site_name: 东莞市瑞凡软件有限公司
site_url: http://www.alpha-optimal.com/zh/
site_description: "东莞市瑞凡软件有限公司，专注于仿真优化软件的开发和应用"

docs_dir: docs/zh

theme:
  name: material
  language: zh
  palette:
    scheme: lime
  font:
    text: '宋体'
  logo: "image/AlphaOptimal.png"
  features:
    - navigation.path
    - navigation.tabs
    - navigation.instant    # 快速切换页面体验 
    - navigation.instant.prefetch
    - navigation.top
    - toc.integrate
  markdown_extensions:
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true

plugins:
  - mermaid2
  - search
      
extra:
  alternate:
    - name: 中文
      link: /zh/ 
      lang: zh
    - name: English
      link: /en/
      lang: en

site_dir: site/en

extra_css:
  - stylesheets/extra.css

nav:
  - 首页: index.md
  - 产品特性:
      - 特性: products/index.md
      - 为什么要用AlphaOptimal: products/WhyUseAlphaOptimal.md
  - 用户文档:  
      - 安装说明: userDocument/other/InstallationWizard.md
      - 用户操作指引:
          - 操作视频: userDocument/videoes/videoes.md
          - 操作文档:
            - 1.刀具管理: userDocument/document/ToolManager_ZH.md
            - 2.导入G代码: userDocument/document/ImportGCode_ZH.md
            - 3.程序树:
                - 程序树概览: userDocument/document/ProgramTree_ZH.md
                - Iso程序段处理: userDocument/document/HandleIsoItem_ZH.md
                - 孔加工程序段处理: userDocument/document/HandleHolesItem_ZH.md
                - 榫头&榫眼程序段处理: userDocument/document/HandleRectItem_ZH.md
                - 桥接程序段处理: userDocument/document/HandleCurveItem_ZH.md
            
      - 机床配置操作指引:
          - 运动链和轴Id解释: userDocument/buildMachineConfig/ChainAndAxisId.md
          - 配置文件编辑器: userDocument/buildMachineConfig/ConfigEditorInterface.md   
          - 示例:双转头机型: 
            - 说明: userDocument/buildMachineConfig/Build_Kinematic_Chain/Build_Dual_Rotation_Chain_0.md
            - 第一步->处理输入模型: userDocument/buildMachineConfig/Build_Kinematic_Chain/Build_Dual_Rotation_Chain_1.md
            - 第二步->新建配置文件: userDocument/buildMachineConfig/Build_Kinematic_Chain/Build_Dual_Rotation_Chain_2.md
          - 示例:单转头单转台机型:
            - 说明: userDocument/buildMachineConfig/Build_Kinematic_Chain/Build_Single_Rotation_Table_0.md
            - 第一步->处理输入模型: userDocument/buildMachineConfig/Build_Kinematic_Chain/Build_Single_Rotation_Table_1.md
            - 第二步->新建配置文件: userDocument/buildMachineConfig/Build_Kinematic_Chain/Build_Single_Rotation_Table_2.md   
      - 用户夹具操作指引:
          - 进入用户夹具编辑器: userDocument/buildUserFixtureConfig/UserFixtureEditor_1.md
          - 参数解释->夹具数据: userDocument/buildUserFixtureConfig/UserFixtureEditor_2.md
          - 参数解释->调整块数据: userDocument/buildUserFixtureConfig/UserFixtureEditor_3.md
          - 参数解释->运动块: userDocument/buildUserFixtureConfig/UserFixtureEditor_4.md   
          - 用户夹具示例:
            - 示例1: userDocument/buildUserFixtureConfig/User_Fixture_Example_1.md
            - 示例2: userDocument/buildUserFixtureConfig/User_Fixture_Example_2.md
      - 其它:
          - 文件&文件夹说明: userDocument/other/index.md
          - data.ini文件说明: userDocument/Instruction_data_file.md
          - 自定义后处理器:
            - 自定义后处理器: userDocument/other/PostProcessor.md
            - 从旧版本提取加工模式: userDocument/other/ExtractByConfig.md   
          - 机床调试:
            - 校正工件坐标原点: userDocument/other/CalibrationWorkpieceCoordinate.md
          - RTCP参数调试: userDocument/other/RTCPParameterDebug.md             
          - Iso代码格式要求: userDocument/other/IsoFormat.md
          - 坐标系详解: userDocument/other/CoordinateSystem.md        
      - 常见问题: 
          - 主轴预启动逻辑: FAQ/主轴预启动逻辑.md
          - 起始&结束位置: FAQ/Program_Start_End.md
          - 加速度转换: FAQ/加速度转换.md
          - 生成ISO代码失败: FAQ/生成ISO代码失败.md
  - 试用版本: Authorization_Application.md
  - 下载和更新: download_update.md
  - 关于: about.md
